version: '2'
services:
   api:
      build: .
      image: handaioh/hint
      container_name: "handaioh_hint"
      ports:
         - "15000:80"
      volumes:
         - "./app/hint_api:/app:ro"
      restart: always
      tty: true
