version: '2'
services:
        api:
                build: .
                container_name: "handaioh_hint"
                ports:
                        - "15001:80"
                volumes:
                        - "./app:/app:ro"
                restart: always
                tty: true
