# Generated by Django 2.1.3 on 2018-11-14 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node', models.CharField(max_length=256)),
                ('hint', models.TextField()),
                ('rank', models.PositiveSmallIntegerField(default=0)),
            ],
        ),
    ]
